apiVersion: v1
kind: Service
metadata:
  namespace: grpc-lb-example
  name: grpc-lb-example-greeter-server-headless-svc
spec:
  selector:
    name: greeter-server
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50051